### ISSUE TITLE
How to create permaLink?

### ISSUE THREAD

**Issue by kadnan** [jbrooksuk/Afro#13]
I want to create a URL something like `http://example.com/name-city` without showing ID in URL. Is it possible in your framework?

**Comment by jbrooksuk** [comment]
Something like:

```php
get('/(a-zA-Z+)', function($Afro) {
    // Get the permalink with $Afro->param(0);
    // Do your database connection and return the content here.
});
```

**Comment by kadnan** [comment]
But I am not passing a Unique ID as input. I want to pass 3 params; UniqueID, City and Name

**Comment by jbrooksuk** [comment]
You can change the regex to capture multiple parameters:

```php
get('/(a-zA-Z+)/(a-zA-Z+)/(a-zA-Z+)', function($Afro) {
    // Get the permalink with $Afro->param(0) $Afro->param(1) $Afro->param(2)
    // Do your database connection and return the content here.
});
```

**Comment by kadnan** [comment]
> get('/(a-zA-Z+)/(a-zA-Z+)/(a-zA-Z+)', function($Afro) {

I guess I am not being able to explain properly. Your example suggests that one should always create a URL with 3 params as output for instance `http://example.com/text1/text2/text3` while what I want to find some way to find ID, City and Name as Input and could have URL with two params only as `http://example.com/name-city` instead of `http://example.com/1234/name-city`

**Comment by jbrooksuk** [comment]
You can do that too. It's just regular expressions, so it doesn't matter how many parameters you setup.
